### ISSUE TITLE
Erro 500 ao buscar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [claytoncalixto/finalwork-client#1]
Caro Clayton, meu nome é Alexandre e estou corrigindo sua atividade.

Seu trabalho já está aceito, parabéns! Mas para ficar 100%, favor incluir o tratamento de exceções. Está retornando erro 500 quando o id não existe. Tanto para a busca do cliente por id (GET), ao atualizar um cliente (UPDATE) e excluí-lo (DELETE).

Além disso, peço que você verifique que está dando um erro nos arquivos de teste. Provavelmente algum import foi removido, pois na criação do projeto por padrão já vem as dependências incluídas. Neste caso, peço que você tente dar maven clean.

Abraço e bons estudos

**Comment by claytoncalixto** [comment]
Alê, boa noite, tudo bem?

Não sei se vai fazer revisão, mas...

Fiz as correções sugeridas onde estava retornando erro status 500 quando o
id não existe. Tanto para a busca do cliente por id (GET), ao atualizar um
cliente (UPDATE) e excluí-lo (DELETE). e subi novamente no git.

Sobre as mensagens de import tive que seguir as recomendações nestes
posts(elas que salvaram a lavoura), pois não gerou a tag no pom.xml
automatico voce disse:
https://cursos.alura.com.br/forum/topico-spring-boot-v-2-4-2-142404
https://cursos.alura.com.br/forum/topico-erro-na-classe-forumapplicationtests-149142

Em qua., 19 de mai. de 2021 às 20:42, Alexandre ***@***.***>
escreveu:
